# Generated by Django 3.0.2 on 2020-01-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('room', 'Room'), ('apartment', 'Apartment'), ('house', 'House')], default='room', max_length=9)),
                ('max_people', models.IntegerField()),
                ('photos', models.TextField(max_length=1024)),
                ('square_meters', models.IntegerField()),
                ('internet_access', models.CharField(choices=[('no', 'No'), ('in_unit', 'In Unit'), ('in_shared_area', 'In Shared Area'), ('upon_request', 'Upon Request')], default='no', max_length=14)),
                ('internet_free_of_charge', models.BooleanField()),
                ('furnishing_sitting_area', models.BooleanField()),
                ('furnishing_sofa', models.BooleanField()),
                ('furnishing_desk', models.BooleanField()),
                ('furnishing_extras', models.TextField(max_length=1024)),
                ('amenity_ac', models.BooleanField()),
                ('amenity_fan', models.BooleanField()),
                ('amenity_tv', models.BooleanField()),
                ('amenity_private_bathroom', models.BooleanField()),
                ('amenity_shower', models.BooleanField()),
                ('amenity_towels', models.BooleanField()),
                ('amenity_mosquito_net', models.BooleanField()),
                ('amenity_private_entry', models.BooleanField()),
                ('amenity_smoking', models.BooleanField()),
                ('amenity_pets', models.BooleanField()),
                ('amenity_wheelchair', models.BooleanField()),
                ('amenity_extras', models.TextField(max_length=1024)),
                ('views', models.TextField(max_length=1024)),
            ],
        ),
    ]
