# Generated by Django 3.0.2 on 2020-01-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0003_facilityphoto_facilityunit_unitphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address_street_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address_zip',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='arrival',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='facility',
            name='cleaning_housekeeping',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='cleaning_laundry',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='contact_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='contact_phone_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='contact_phone_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='directions',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='facility',
            name='languages',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='facility',
            name='parking',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='policies',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_24h_front_desk',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_airport_shuttle',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_bar',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_beach',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_extras',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_fitness_room',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_kids_playground',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_restaurant_meal_breakfast',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_restaurant_meal_dinner',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_restaurant_meal_lunch',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_restaurant_prices',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_restaurant_times',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='facility',
            name='speciality_swimming_pool',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_ac',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_extras',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_fan',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_mosquito_net',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_pets',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_private_bathroom',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_private_entry',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_shower',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_smoking',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_towels',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_tv',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='amenity_wheelchair',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='furnishing_desk',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='furnishing_extras',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='unit',
            name='furnishing_sitting_area',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='furnishing_sofa',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='internet_access',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('in_unit', 'In Unit'), ('in_shared_area', 'In Shared Area'), ('upon_request', 'Upon Request')], max_length=14),
        ),
        migrations.AlterField(
            model_name='unit',
            name='internet_free_of_charge',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='kind',
            field=models.CharField(choices=[('room', 'Room'), ('apartment', 'Apartment'), ('house', 'House'), ('other', 'Other')], default='room', max_length=9),
        ),
        migrations.AlterField(
            model_name='unit',
            name='max_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='photos',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='unit',
            name='square_meters',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='views',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
