# Generated by Django 3.0.2 on 2020-01-11 15:32

from django.db import migrations, models
import django.db.models.deletion
import hotel_africa.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0005_auto_20200109_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='facility',
            name='contact_phone_3',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='photos',
        ),
        migrations.AlterField(
            model_name='facilityphoto',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_africa.Facility'),
        ),
        migrations.AlterField(
            model_name='facilityphoto',
            name='image',
            field=models.ImageField(upload_to=hotel_africa.models.upload_facilityphoto_path_handler),
        ),
        migrations.AlterField(
            model_name='unit',
            name='square_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='image',
            field=models.ImageField(upload_to=hotel_africa.models.upload_unitphoto_path_handler),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_africa.Unit'),
        ),
        migrations.CreateModel(
            name='FacilityLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_africa.Facility')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_africa.Language')),
            ],
        ),
    ]
