# Generated by Django 3.0.2 on 2020-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0006_auto_20200111_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='l2',
            field=models.ManyToManyField(to='hotel_africa.Language'),
        ),
    ]
