# Generated by Django 3.0.2 on 2020-01-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0007_facility_l2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='languages',
        ),
        migrations.DeleteModel(
            name='FacilityLanguages',
        ),
    ]
