# Generated by Django 3.0.2 on 2020-01-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0008_auto_20200111_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='l2',
            new_name='languages',
        ),
    ]
