# Generated by Django 3.0.2 on 2020-01-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0009_auto_20200111_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='beds',
            field=models.ManyToManyField(to='hotel_africa.Bed'),
        ),
    ]
