# Generated by Django 3.0.2 on 2020-01-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0010_auto_20200111_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('king', 'King'), ('other', 'Other')], max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='beds',
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.AddField(
            model_name='unitbed',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_africa.Unit'),
        ),
    ]
