# Generated by Django 3.0.2 on 2020-01-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0011_auto_20200111_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('german', 'De'), ('french', 'Fr'), ('english', 'En'), ('spanish', 'Es')], max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='facility',
            name='languages',
        ),
        migrations.AlterField(
            model_name='unitbed',
            name='bed',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('king', 'King'), ('other', 'Other')], max_length=14),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='facilitylanguage',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_africa.Facility'),
        ),
    ]
