# Generated by Django 3.0.2 on 2020-01-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0013_auto_20200113_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unitrates',
            field=models.ManyToManyField(to='hotel_africa.UnitRate'),
        ),
    ]
