# Generated by Django 3.0.2 on 2020-01-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0014_unit_unitrates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('checkin_from', models.DateField()),
                ('checkout_at', models.DateField()),
                ('status', models.CharField(choices=[('None', 'None'), ('Booked', 'Booked'), ('Canceled', 'Canceled'), ('No show', 'No Show'), ('Completed', 'Completed')], default='None', max_length=25)),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Creditcard'), ('Paypal', 'Paypal'), ('Wire transfer', 'Wire Transfer'), ('Western Union', 'Western Union')], default='Cash', max_length=25)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_africa.Unit')),
                ('unitrate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_africa.UnitRate')),
            ],
        ),
    ]
