# Generated by Django 3.0.2 on 2020-01-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0018_auto_20200113_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='views',
        ),
        migrations.AlterField(
            model_name='unitrate',
            name='free_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
