# Generated by Django 3.0.2 on 2020-01-15 15:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0019_auto_20200115_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='checkin_from',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='checkout_at',
            new_name='departure_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_persons',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.IntegerField(),
        ),
    ]
