# Generated by Django 3.0.2 on 2020-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0020_auto_20200115_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_persons',
            field=models.IntegerField(),
        ),
    ]
