# Generated by Django 3.0.2 on 2020-01-15 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0021_auto_20200115_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
