# Generated by Django 3.0.2 on 2020-01-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0022_auto_20200115_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Creditcard'), ('Paypal', 'Paypal'), ('Wire transfer', 'Wire Transfer'), ('Western Union', 'Western Union')], max_length=25),
        ),
    ]
