# Generated by Django 3.0.2 on 2020-01-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0024_booking_total_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=-1, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price_currency',
            field=models.CharField(choices=[('USD (USA)', 'Usd'), ('EUR (Europe)', 'Eur'), ('XOF (CFA Franc)', 'Xof'), ('NGN (Nigeria)', 'Ngn'), ('MWK (Malawi)', 'Mwk')], default='USD (USA)', editable=False, max_length=25),
        ),
    ]
