# Generated by Django 3.0.2 on 2020-01-15 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_africa', '0026_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2048)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('refer_booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_africa.Booking')),
                ('refer_facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_africa.Facility')),
                ('refer_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_africa.Unit')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
