# Generated by Django 3.0.2 on 2020-01-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0029_auto_20200115_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
