# Generated by Django 3.0.2 on 2020-01-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0030_auto_20200117_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='checkout_at',
            new_name='checkout_from',
        ),
    ]
