# Generated by Django 3.0.2 on 2020-01-17 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_africa', '0031_auto_20200117_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='checkin_to',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='checkout_to',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
